export const languages={de:'Deutsch',en:'English',tr:'Türkçe',ro:'Română',uk:'Українська',es:'Español',sv:'Svenska',da:'Dansk'};
export const routes=['','pc-reparatur-augsburg','handyreparatur-augsburg','konsolenreparatur-augsburg','datenrettung-augsburg','reparaturanfrage','impressum','datenschutz','rechtliches'];
export const prices=[30,0,59,59,89,59,59,89,59,69,79,59,59,69,49,55,250,49,69,49,69,39,79];
export const localeContent={
en:{
labels:'Services|Prices|How it works|Questions|Contact|Request a repair|Call now|Learn more|Home|Legal notice|Privacy policy|Customer reviews|Repair reports|Language|from|Free|Send an enquiry|Directions|German original|Back|Online repair enquiry|Device & fault|Contact details|Open menu|Close menu'.split('|'),
hero:'Computer, phone and console repairs in Augsburg',intro:'Personal service from Maurice Keil. Tell us what is wrong with your device. We assess the fault, explain the options and agree the next steps with you.',hours:'Monday–Saturday, 09:00–20:00. Walk-ins are welcome; an enquiry in advance is recommended.',
services:[['PC & laptop repair','Windows, drivers, software, SSD upgrades, RAM, cleaning and maintenance.','A slow computer does not always need replacing. We check the cause and explain whether software work, a faster drive, more memory or cleaning is worthwhile. SSD installation can include cloning the existing system. Back up important files beforehand if possible. Timing depends on the fault, work and available parts.'],['Phone & tablet repair','Screen and battery replacement, charging ports, back glass and system faults.','Tell us the exact model, fault and any visible damage. Repair options and total cost depend on the device and required parts. We inspect it before agreeing the work. Back up important files if you can; do not send passwords, PINs or unlock codes.'],['Console repair','PlayStation and Xbox cleaning, repairs, thermal paste and HDMI ports.','Loud fans, overheating, unexpected shutdowns or no picture can have several causes. We check the model and symptoms first. Cleaning, thermal paste replacement or HDMI repair may be suitable depending on its condition. We agree the expected cost before starting.'],['Software-based data recovery','Assessment of deleted files and logically inaccessible drives.','Stop using the affected drive if possible. Do not install software, run repair tools or save new files. Recovery may be possible where the original data has not been fully overwritten. Results depend on the drive and file system; success is not guaranteed. We do not open drives or repair physical, electronic or mechanical damage. Such cases require a specialist laboratory.']],
priceNames:'Fault diagnosis|Advice|System check|Data backup|Windows installation|Driver installation|Software installation|SSD installation including cloning|RAM upgrade|Cleaning & maintenance|Screen replacement|Battery replacement|Charging port repair|Back glass repair|Software / system faults|Data recovery assessment|Successful software-based data recovery|PlayStation cleaning|PlayStation repair|Xbox cleaning|Xbox repair|Thermal paste replacement|HDMI port repair'.split('|'),
fees:'Fault diagnosis costs €30 if no repair follows; this fee is waived when we carry out the repair. Data recovery: €55 for assessment alone or an unsuccessful attempt. Successful software-based recovery costs €250 in total, including assessment.',terms:'All prices are final prices; no VAT is shown under section 19 of the German VAT Act (UStG). Prices marked “from” may increase for model-specific parts and additional work. We agree the expected total after inspection. Repairs and chargeable additional work begin only with your approval.',
steps:['Describe the device and fault online, by phone or by email.','We inspect the device and explain the practical options.','You decide after we have discussed the work and costs.','We carry out the agreed repair, test the device and return it.'],
faq:[['Can I come without an appointment?','Yes. Contacting us first helps us plan enough time for your device.'],['How long does a repair take?','It depends on the fault and availability of parts. We give you a realistic estimate after assessment.'],['Will my data be kept confidential?','We handle devices and stored data carefully and confidentially. Please back up important files where possible; data preservation cannot be guaranteed.'],['Is data recovery guaranteed?','No. The relevant storage areas must still exist and be readable. Fully overwritten data cannot be restored by this service.'],['Does an enquiry commit me to a repair?','No. Sending the form is only an enquiry. Paid work starts after your approval.']],
formIntro:'Describe the device and fault, then add your contact details. This enquiry is non-binding.',original:'The following text is the German original. It is explicitly marked as German and is not presented as a translation.',originals:'Customer reviews and workshop reports remain available in their original language.',privacyAck:'I have read the privacy policy (German original).',languageNote:'These pages provide information in your selected language. They do not promise that telephone support is available in that language.'},
tr:{
labels:'Hizmetler|Fiyatlar|Süreç|Sorular|İletişim|Onarım talebi|Hemen arayın|Ayrıntılar|Ana sayfa|Yasal bilgiler|Gizlilik politikası|Müşteri yorumları|Onarım raporları|Dil|başlangıç|Ücretsiz|Talep gönderin|Yol tarifi|Almanca aslı|Geri|Çevrimiçi onarım talebi|Cihaz ve arıza|İletişim bilgileri|Menüyü aç|Menüyü kapat'.split('|'),
hero:'Augsburg’da bilgisayar, telefon ve oyun konsolu onarımı',intro:'Maurice Keil’den kişisel hizmet. Cihazınızdaki sorunu anlatın. Arızayı inceler, seçenekleri açıklar ve sonraki adımları sizinle kararlaştırırız.',hours:'Pazartesi–Cumartesi 09.00–20.00. Randevusuz gelebilirsiniz; önceden talep göndermenizi öneririz.',
services:[['PC ve dizüstü bilgisayar onarımı','Windows, sürücüler, yazılımlar, SSD, RAM, temizlik ve bakım.','Yavaşlayan bir bilgisayarı her zaman değiştirmek gerekmez. Önce nedeni inceler; yazılım işlemi, daha hızlı disk, ek bellek veya temizliğin yararlı olup olmayacağını açıklarız. SSD montajı mevcut sistemin klonlanmasını içerebilir. Mümkünse önemli dosyalarınızı önceden yedekleyin. Süre arızaya, işin kapsamına ve parçalara bağlıdır.'],['Telefon ve tablet onarımı','Ekran ve pil değişimi, şarj soketi, arka cam ve sistem sorunları.','Tam modeli, arızayı ve görünen hasarları belirtin. Onarım seçenekleri ve toplam tutar cihaza ve parçalara bağlıdır. İşlemi kararlaştırmadan önce cihazı inceleriz. Mümkünse verilerinizi yedekleyin; parola, PIN veya kilit açma kodu göndermeyin.'],['Oyun konsolu onarımı','PlayStation ve Xbox temizliği, onarımı, termal macun ve HDMI soketi.','Gürültülü fan, aşırı ısınma, beklenmedik kapanma veya görüntü olmamasının farklı nedenleri olabilir. Önce modeli ve belirtileri inceleriz. Duruma göre temizlik, termal macun değişimi veya HDMI onarımı uygun olabilir. Başlamadan önce tahmini tutarı kararlaştırırız.'],['Yazılım tabanlı veri kurtarma','Silinen dosyaların ve mantıksal olarak erişilemeyen disklerin analizi.','Mümkünse etkilenen diski kullanmayı bırakın. Yazılım yüklemeyin, onarım araçları çalıştırmayın ve yeni dosya kaydetmeyin. Eski verilerin tamamen üzerine yazılmamışsa kurtarma mümkün olabilir. Sonuç diske ve dosya sistemine bağlıdır; başarı garantisi yoktur. Disk açma veya fiziksel, elektronik ya da mekanik hasar onarımı yapmıyoruz. Bu durumlar uzman laboratuvar gerektirir.']],
priceNames:'Arıza tespiti|Danışmanlık|Sistem kontrolü|Veri yedekleme|Windows kurulumu|Sürücü kurulumu|Yazılım kurulumu|Klonlama dahil SSD montajı|RAM yükseltme|Temizlik ve bakım|Ekran değişimi|Pil değişimi|Şarj soketi onarımı|Arka cam onarımı|Yazılım / sistem hataları|Veri kurtarma analizi|Başarılı yazılım tabanlı veri kurtarma|PlayStation temizliği|PlayStation onarımı|Xbox temizliği|Xbox onarımı|Termal macun değişimi|HDMI soketi onarımı'.split('|'),
fees:'Onarım yapılmazsa arıza tespiti 30 €; onarım yapılırsa bu ücret alınmaz. Veri kurtarma: yalnızca analiz veya başarısız kurtarma için 55 €. Başarılı yazılım tabanlı kurtarmada analiz dahil toplam 250 €.',terms:'Fiyatlar nihai fiyatlardır; Alman KDV Kanunu’nun (UStG) 19. maddesi uyarınca KDV ayrıca gösterilmez. Başlangıç fiyatlarına modele özel parçalar ve ek işçilik eklenebilir. İnceleme sonrası tahmini toplam tutarı kararlaştırırız. Onarım ve ücretli ek işler yalnızca onayınızla başlar.',
steps:['Cihazı ve arızayı çevrimiçi, telefonla veya e-postayla anlatın.','Cihazı inceler ve uygun seçenekleri açıklarız.','İş ve ücret hakkında bilgi aldıktan sonra karar verirsiniz.','Kararlaştırılan onarımı yapar, cihazı test eder ve teslim ederiz.'],
faq:[['Randevusuz gelebilir miyim?','Evet. Önceden haber vermeniz cihazınız için yeterli zaman ayırmamızı sağlar.'],['Onarım ne kadar sürer?','Arızaya ve parça teminine bağlıdır. İnceleme sonrası gerçekçi bir süre bildiririz.'],['Verilerim gizli tutulur mu?','Cihazları ve kayıtlı verileri özenle ve gizlilikle işleriz. Mümkünse önemli dosyaları yedekleyin; verilerin korunması garanti edilemez.'],['Veri kurtarma garantili mi?','Hayır. İlgili depolama alanları mevcut ve okunabilir olmalıdır. Tamamen üzerine yazılmış veriler bu hizmetle geri getirilemez.'],['Talep göndermek onarım siparişi midir?','Hayır. Form yalnızca bir taleptir. Ücretli işlere onayınızdan sonra başlanır.']],
formIntro:'Cihazı ve arızayı açıklayın, ardından iletişim bilgilerinizi ekleyin. Talep bağlayıcı değildir.',original:'Aşağıdaki metin Almanca aslıdır. Almanca olduğu açıkça belirtilir; çeviri olarak sunulmaz.',originals:'Müşteri yorumları ve atölye raporları özgün dilinde sunulur.',privacyAck:'Gizlilik politikasını (Almanca aslı) okudum.',languageNote:'Bu sayfalar seçtiğiniz dilde bilgi verir. Bu dilde telefon desteği sunulacağı taahhüt edilmez.'},

ro:{
labels:'Servicii|Prețuri|Etape|Întrebări|Contact|Solicită o reparație|Sună acum|Detalii|Acasă|Informații legale|Confidențialitate|Recenzii|Rapoarte de reparații|Limbă|de la|Gratuit|Trimite o solicitare|Indicații de orientare|Original în germană|Înapoi|Solicitare de reparație online|Dispozitiv și problemă|Date de contact|Deschide meniul|Închide meniul'.split('|'),
hero:'Reparații de calculatoare, telefoane și console în Augsburg',intro:'Servicii personale oferite de Maurice Keil. Descrieți problema dispozitivului. Verificăm defecțiunea, explicăm opțiunile și stabilim împreună pașii următori.',hours:'Luni–sâmbătă, 09:00–20:00. Puteți veni fără programare; recomandăm o solicitare în prealabil.',
services:[['Reparații PC și laptop','Windows, drivere, programe, SSD, RAM, curățare și întreținere.','Un calculator lent nu trebuie întotdeauna înlocuit. Verificăm cauza și explicăm dacă sunt utile intervențiile software, un disc mai rapid, mai multă memorie sau curățarea. Instalarea unui SSD poate include clonarea sistemului existent. Salvați fișierele importante în prealabil, dacă este posibil. Durata depinde de defecțiune, lucrări și piese.'],['Reparații telefoane și tablete','Înlocuire ecran și baterie, port de încărcare, sticlă spate și erori de sistem.','Indicați modelul exact, defecțiunea și deteriorările vizibile. Opțiunile și costul total depind de dispozitiv și de piesele necesare. Verificăm dispozitivul înainte de a stabili lucrarea. Faceți o copie de siguranță, dacă puteți; nu trimiteți parole, PIN-uri sau coduri de deblocare.'],['Reparații console','Curățare și reparații PlayStation și Xbox, pastă termică și porturi HDMI.','Ventilatoarele zgomotoase, supraîncălzirea, opririle neașteptate sau lipsa imaginii pot avea mai multe cauze. Verificăm mai întâi modelul și simptomele. În funcție de stare, pot fi potrivite curățarea, înlocuirea pastei termice sau repararea portului HDMI. Stabilim costul estimat înainte de începere.'],['Recuperare de date prin software','Analiza fișierelor șterse și a unităților inaccesibile din cauze logice.','Opriți utilizarea suportului afectat, dacă este posibil. Nu instalați programe, nu porniți instrumente de reparare și nu salvați fișiere noi. Recuperarea poate fi posibilă dacă datele originale nu au fost suprascrise complet. Rezultatul depinde de suport și de sistemul de fișiere; succesul nu este garantat. Nu deschidem unități și nu reparăm deteriorări fizice, electronice sau mecanice. Aceste cazuri necesită un laborator specializat.']],
priceNames:'Diagnosticarea defecțiunii|Consultanță|Verificare sistem|Copie de siguranță|Instalare Windows|Instalare drivere|Instalare software|Montare SSD cu clonare|Extindere RAM|Curățare și întreținere|Înlocuire ecran|Înlocuire baterie|Reparare port de încărcare|Reparare sticlă spate|Erori software / sistem|Analiză pentru recuperarea datelor|Recuperare reușită de date prin software|Curățare PlayStation|Reparație PlayStation|Curățare Xbox|Reparație Xbox|Înlocuire pastă termică|Reparare port HDMI'.split('|'),
fees:'Diagnosticul costă 30 € dacă nu urmează o reparație; taxa nu se aplică dacă efectuăm reparația. Recuperare de date: 55 € pentru analiză sau recuperare nereușită. Recuperarea reușită prin software costă în total 250 €, inclusiv analiza.',terms:'Toate prețurile sunt finale; TVA nu este evidențiată conform § 19 din legea germană UStG. La prețurile „de la” se pot adăuga piese specifice modelului și lucrări suplimentare. Stabilim totalul estimat după verificare. Reparațiile și lucrările suplimentare contra cost încep numai cu acordul dumneavoastră.',
steps:['Descrieți dispozitivul și problema online, telefonic sau prin e-mail.','Verificăm dispozitivul și explicăm opțiunile potrivite.','Decideți după ce discutăm lucrările și costurile.','Efectuăm reparația convenită, testăm dispozitivul și îl returnăm.'],
faq:[['Pot veni fără programare?','Da. Contactarea în prealabil ne ajută să alocăm suficient timp dispozitivului.'],['Cât durează reparația?','Depinde de defecțiune și de disponibilitatea pieselor. După analiză oferim o estimare realistă.'],['Datele mele sunt confidențiale?','Tratăm dispozitivele și datele cu grijă și confidențialitate. Salvați fișierele importante dacă este posibil; păstrarea datelor nu poate fi garantată.'],['Recuperarea datelor este garantată?','Nu. Zonele de stocare relevante trebuie să existe și să fie lizibile. Datele suprascrise complet nu pot fi recuperate prin acest serviciu.'],['Solicitarea mă obligă la reparație?','Nu. Formularul este doar o solicitare. Lucrările contra cost încep după acordul dumneavoastră.']],
formIntro:'Descrieți dispozitivul și problema, apoi completați datele de contact. Solicitarea nu implică obligații.',original:'Textul următor este originalul în germană. Este marcat ca atare și nu este prezentat drept traducere.',originals:'Recenziile clienților și rapoartele atelierului sunt disponibile în limba originală.',privacyAck:'Am citit politica de confidențialitate (originalul în germană).',languageNote:'Aceste pagini oferă informații în limba selectată. Ele nu garantează asistență telefonică în această limbă.'},
uk:{
labels:'Послуги|Ціни|Порядок роботи|Запитання|Контакти|Запит на ремонт|Зателефонувати|Докладніше|Головна|Юридична інформація|Конфіденційність|Відгуки клієнтів|Звіти про ремонти|Мова|від|Безкоштовно|Надіслати запит|Маршрут|Німецький оригінал|Назад|Онлайн-запит на ремонт|Пристрій і несправність|Контактні дані|Відкрити меню|Закрити меню'.split('|'),
hero:'Ремонт комп’ютерів, телефонів і консолей в Аугсбурзі',intro:'Особисте обслуговування від Maurice Keil. Опишіть проблему з пристроєм. Ми перевіримо несправність, пояснимо варіанти та узгодимо з вами наступні кроки.',hours:'Понеділок–субота, 09:00–20:00. Можна прийти без запису; радимо попередньо надіслати запит.',
services:[['Ремонт ПК і ноутбуків','Windows, драйвери, програми, SSD, RAM, чищення й обслуговування.','Повільний комп’ютер не завжди потрібно замінювати. Спочатку з’ясовуємо причину та пояснюємо, чи допоможуть налаштування програм, швидший накопичувач, додаткова пам’ять або чищення. Встановлення SSD може включати клонування наявної системи. За можливості заздалегідь збережіть важливі файли. Тривалість залежить від несправності, робіт і наявності деталей.'],['Ремонт телефонів і планшетів','Заміна екрана й акумулятора, роз’єм заряджання, заднє скло та системні помилки.','Вкажіть точну модель, несправність і видимі пошкодження. Варіанти ремонту та загальна вартість залежать від пристрою й потрібних деталей. Перед узгодженням робіт перевіряємо пристрій. За можливості створіть резервну копію; не надсилайте паролі, PIN-коди або коди розблокування.'],['Ремонт ігрових консолей','Чищення й ремонт PlayStation та Xbox, термопаста й роз’єми HDMI.','Шумні вентилятори, перегрів, раптове вимкнення чи відсутність зображення можуть мати різні причини. Спочатку перевіряємо модель і симптоми. Залежно від стану можуть допомогти чищення, заміна термопасти чи ремонт HDMI. Орієнтовну вартість погоджуємо до початку робіт.'],['Програмне відновлення даних','Аналіз видалених файлів і накопичувачів із логічними проблемами доступу.','За можливості припиніть використання проблемного накопичувача. Не встановлюйте програми, не запускайте засоби виправлення та не записуйте нові файли. Відновлення може бути можливим, якщо початкові дані не перезаписані повністю. Результат залежить від накопичувача й файлової системи; успіх не гарантується. Ми не відкриваємо накопичувачі й не усуваємо фізичні, електронні або механічні пошкодження. Такі випадки потребують спеціалізованої лабораторії.']],
priceNames:'Діагностика несправності|Консультація|Перевірка системи|Резервне копіювання|Встановлення Windows|Встановлення драйверів|Встановлення програм|Встановлення SSD із клонуванням|Збільшення RAM|Чищення й обслуговування|Заміна екрана|Заміна акумулятора|Ремонт роз’єму заряджання|Ремонт заднього скла|Програмні / системні помилки|Аналіз для відновлення даних|Успішне програмне відновлення даних|Чищення PlayStation|Ремонт PlayStation|Чищення Xbox|Ремонт Xbox|Заміна термопасти|Ремонт роз’єму HDMI'.split('|'),
fees:'Діагностика коштує 30 €, якщо ремонт не виконується; у разі ремонту ця плата не стягується. Відновлення даних: 55 € за аналіз або невдалу спробу. Успішне програмне відновлення коштує загалом 250 €, включно з аналізом.',terms:'Усі ціни кінцеві; ПДВ не зазначається відповідно до § 19 німецького закону UStG. До цін «від» можуть додаватися деталі для конкретної моделі та додаткові роботи. Орієнтовну загальну суму узгоджуємо після перевірки. Ремонт і платні додаткові роботи починаємо лише за вашою згодою.',
steps:['Опишіть пристрій і несправність онлайн, телефоном або електронною поштою.','Ми перевіримо пристрій і пояснимо доцільні варіанти.','Ви ухвалите рішення після обговорення робіт і вартості.','Ми виконаємо погоджений ремонт, перевіримо пристрій і повернемо його.'],
faq:[['Чи можна прийти без запису?','Так. Попередній контакт допоможе нам виділити достатньо часу для вашого пристрою.'],['Скільки триває ремонт?','Це залежить від несправності й наявності деталей. Після перевірки повідомимо реалістичний термін.'],['Чи залишаться мої дані конфіденційними?','Ми дбайливо й конфіденційно працюємо з пристроями та даними. За можливості збережіть важливі файли; збереження даних не гарантується.'],['Чи гарантоване відновлення даних?','Ні. Відповідні ділянки пам’яті мають залишатися доступними для читання. Повністю перезаписані дані цим способом не відновлюються.'],['Чи зобов’язує запит замовити ремонт?','Ні. Форма — лише запит. Платні роботи починаються після вашої згоди.']],
formIntro:'Опишіть пристрій і несправність, потім додайте контактні дані. Запит не зобов’язує до замовлення.',original:'Нижче наведено німецький оригінал. Його позначено як текст німецькою, а не як переклад.',originals:'Відгуки клієнтів і звіти майстерні доступні мовою оригіналу.',privacyAck:'Я ознайомився/ознайомилася з політикою конфіденційності (німецький оригінал).',languageNote:'Ці сторінки надають інформацію вибраною мовою. Вони не гарантують телефонного обслуговування цією мовою.'},

es:{
labels:'Servicios|Precios|Proceso|Preguntas|Contacto|Solicitar reparación|Llamar ahora|Más información|Inicio|Aviso legal|Privacidad|Opiniones|Informes de reparación|Idioma|desde|Gratis|Enviar consulta|Cómo llegar|Original en alemán|Volver|Solicitud de reparación en línea|Dispositivo y avería|Datos de contacto|Abrir menú|Cerrar menú'.split('|'),
hero:'Reparación de ordenadores, móviles y consolas en Augsburgo',intro:'Atención personal de Maurice Keil. Describa el problema de su dispositivo. Evaluamos la avería, explicamos las opciones y acordamos los siguientes pasos con usted.',hours:'Lunes a sábado, de 09:00 a 20:00. Puede venir sin cita; recomendamos enviar una consulta previamente.',
services:[['Reparación de PC y portátiles','Windows, controladores, programas, SSD, RAM, limpieza y mantenimiento.','Un ordenador lento no siempre necesita ser sustituido. Comprobamos la causa y explicamos si conviene intervenir en el software, instalar un disco más rápido, ampliar la memoria o limpiar el equipo. La instalación de SSD puede incluir la clonación del sistema. Haga una copia de los archivos importantes si es posible. El plazo depende de la avería, el trabajo y las piezas.'],['Reparación de móviles y tabletas','Cambio de pantalla y batería, puerto de carga, cristal trasero y fallos del sistema.','Indique el modelo exacto, la avería y los daños visibles. Las opciones y el precio total dependen del dispositivo y de los repuestos necesarios. Revisamos el equipo antes de acordar el trabajo. Haga una copia de seguridad si puede; no envíe contraseñas, PIN ni códigos de desbloqueo.'],['Reparación de consolas','Limpieza y reparación de PlayStation y Xbox, pasta térmica y puertos HDMI.','El ruido del ventilador, el sobrecalentamiento, los apagados inesperados o la ausencia de imagen pueden tener varias causas. Primero revisamos el modelo y los síntomas. Según el estado, puede ser adecuada una limpieza, el cambio de pasta térmica o una reparación HDMI. Acordamos el coste estimado antes de empezar.'],['Recuperación de datos por software','Análisis de archivos borrados y unidades con problemas de acceso lógico.','Deje de utilizar la unidad afectada si es posible. No instale programas, ejecute herramientas de reparación ni guarde archivos nuevos. La recuperación puede ser posible si los datos originales no se han sobrescrito por completo. El resultado depende de la unidad y del sistema de archivos; no se garantiza el éxito. No abrimos unidades ni reparamos daños físicos, electrónicos o mecánicos. Esos casos requieren un laboratorio especializado.']],
priceNames:'Diagnóstico de averías|Asesoramiento|Revisión del sistema|Copia de seguridad|Instalación de Windows|Instalación de controladores|Instalación de software|Instalación de SSD con clonación|Ampliación de RAM|Limpieza y mantenimiento|Cambio de pantalla|Cambio de batería|Reparación del puerto de carga|Reparación del cristal trasero|Fallos de software / sistema|Análisis de recuperación de datos|Recuperación de datos por software con éxito|Limpieza de PlayStation|Reparación de PlayStation|Limpieza de Xbox|Reparación de Xbox|Cambio de pasta térmica|Reparación del puerto HDMI'.split('|'),
fees:'El diagnóstico cuesta 30 € si no se realiza una reparación; si la realizamos, no se cobra esta tarifa. Recuperación de datos: 55 € por el análisis o un intento sin éxito. La recuperación por software con éxito cuesta 250 € en total, incluido el análisis.',terms:'Todos los precios son finales; no se desglosa IVA conforme al artículo 19 de la ley alemana UStG. Los precios «desde» pueden aumentar por piezas específicas del modelo y trabajos adicionales. Acordamos el total estimado tras la revisión. Las reparaciones y trabajos adicionales de pago solo comienzan con su autorización.',
steps:['Describa el dispositivo y la avería en línea, por teléfono o por correo electrónico.','Revisamos el dispositivo y explicamos las opciones adecuadas.','Usted decide después de hablar de los trabajos y sus costes.','Realizamos la reparación acordada, probamos el dispositivo y se lo devolvemos.'],
faq:[['¿Puedo acudir sin cita?','Sí. Contactar antes nos permite reservar tiempo suficiente para su dispositivo.'],['¿Cuánto tarda la reparación?','Depende de la avería y de la disponibilidad de piezas. Tras la revisión ofrecemos una estimación realista.'],['¿Se mantendrá la confidencialidad de mis datos?','Tratamos los equipos y los datos con cuidado y confidencialidad. Haga una copia de los archivos importantes si puede; no se garantiza su conservación.'],['¿Está garantizada la recuperación de datos?','No. Las zonas de almacenamiento deben seguir existiendo y ser legibles. Los datos sobrescritos por completo no se recuperan con este servicio.'],['¿La solicitud me obliga a contratar una reparación?','No. El formulario es solo una consulta. Los trabajos de pago empiezan después de su autorización.']],
formIntro:'Describa el dispositivo y la avería y añada sus datos de contacto. La solicitud no es vinculante.',original:'El siguiente texto es el original en alemán. Se identifica como tal y no se presenta como una traducción.',originals:'Las opiniones de clientes y los informes del taller están disponibles en su idioma original.',privacyAck:'He leído la política de privacidad (original en alemán).',languageNote:'Estas páginas ofrecen información en el idioma elegido. No garantizan atención telefónica en ese idioma.'},
sv:{
labels:'Tjänster|Priser|Så går det till|Frågor|Kontakt|Begär reparation|Ring nu|Läs mer|Startsida|Juridisk information|Integritetspolicy|Kundomdömen|Reparationsrapporter|Språk|från|Kostnadsfritt|Skicka förfrågan|Hitta hit|Tyskt original|Tillbaka|Reparationsförfrågan online|Enhet och fel|Kontaktuppgifter|Öppna menyn|Stäng menyn'.split('|'),
hero:'Reparation av datorer, mobiler och spelkonsoler i Augsburg',intro:'Personlig service av Maurice Keil. Beskriv vad som är fel på din enhet. Vi undersöker felet, förklarar alternativen och kommer överens om nästa steg med dig.',hours:'Måndag–lördag 09.00–20.00. Du är välkommen utan tidsbokning; vi rekommenderar kontakt i förväg.',
services:[['PC- och laptopreparation','Windows, drivrutiner, program, SSD, RAM, rengöring och underhåll.','En långsam dator behöver inte alltid bytas ut. Vi undersöker orsaken och förklarar om programåtgärder, en snabbare disk, mer minne eller rengöring är lämpligt. SSD-installation kan omfatta kloning av det befintliga systemet. Säkerhetskopiera viktiga filer i förväg om möjligt. Tiden beror på felet, arbetet och tillgången på delar.'],['Mobil- och surfplattereparation','Byte av skärm och batteri, laddningsport, bakglas och systemfel.','Ange exakt modell, fel och synliga skador. Alternativen och totalpriset beror på enheten och reservdelarna. Vi undersöker enheten innan arbetet bestäms. Säkerhetskopiera om möjligt; skicka inga lösenord, PIN-koder eller upplåsningskoder.'],['Reparation av spelkonsoler','Rengöring och reparation av PlayStation och Xbox, kylpasta och HDMI-portar.','Högljudda fläktar, överhettning, oväntade avstängningar eller utebliven bild kan ha flera orsaker. Vi kontrollerar först modell och symtom. Beroende på skicket kan rengöring, byte av kylpasta eller HDMI-reparation vara lämpligt. Vi kommer överens om den beräknade kostnaden före arbetet.'],['Programvarubaserad dataåterställning','Analys av raderade filer och enheter med logiska åtkomstproblem.','Sluta använda den berörda lagringsenheten om möjligt. Installera inte program, kör inte reparationsverktyg och spara inga nya filer. Återställning kan vara möjlig om ursprungsdata inte har skrivits över helt. Resultatet beror på lagringsenheten och filsystemet; framgång garanteras inte. Vi öppnar inte diskar eller reparerar fysiska, elektroniska eller mekaniska skador. Sådana fall kräver ett specialiserat laboratorium.']],
priceNames:'Felsökning|Rådgivning|Systemkontroll|Säkerhetskopiering|Windows-installation|Installation av drivrutiner|Programinstallation|SSD-installation med kloning|RAM-uppgradering|Rengöring och underhåll|Skärmbyte|Batteribyte|Reparation av laddningsport|Reparation av bakglas|Program- / systemfel|Analys för dataåterställning|Lyckad programvarubaserad dataåterställning|PlayStation-rengöring|PlayStation-reparation|Xbox-rengöring|Xbox-reparation|Byte av kylpasta|HDMI-portreparation'.split('|'),
fees:'Felsökning kostar 30 € om ingen reparation följer; avgiften bortfaller om vi utför reparationen. Dataåterställning: 55 € för enbart analys eller ett misslyckat försök. Lyckad programvarubaserad återställning kostar totalt 250 €, inklusive analys.',terms:'Alla priser är slutpriser; moms redovisas inte enligt § 19 i tyska UStG. Frånpriser kan öka för modellspecifika delar och extra arbete. Vi kommer överens om beräknat totalpris efter undersökning. Reparationer och debiterbart extraarbete påbörjas endast med ditt godkännande.',
steps:['Beskriv enheten och felet online, per telefon eller via e-post.','Vi undersöker enheten och förklarar lämpliga alternativ.','Du bestämmer efter att vi har gått igenom arbete och kostnader.','Vi utför avtalad reparation, testar enheten och lämnar tillbaka den.'],
faq:[['Kan jag komma utan bokning?','Ja. Kontakt i förväg hjälper oss att avsätta tillräckligt med tid för din enhet.'],['Hur lång tid tar reparationen?','Det beror på felet och tillgången på reservdelar. Efter undersökningen får du en realistisk uppskattning.'],['Behandlas mina data konfidentiellt?','Vi hanterar enheter och data omsorgsfullt och konfidentiellt. Säkerhetskopiera viktiga filer om möjligt; databevarande kan inte garanteras.'],['Garanteras dataåterställning?','Nej. De berörda lagringsområdena måste finnas kvar och gå att läsa. Helt överskrivna data kan inte återställas med tjänsten.'],['Förbinder en förfrågan mig till reparation?','Nej. Formuläret är endast en förfrågan. Betalt arbete börjar efter ditt godkännande.']],
formIntro:'Beskriv enheten och felet och fyll sedan i kontaktuppgifterna. Förfrågan är inte bindande.',original:'Följande text är det tyska originalet. Den är märkt som tysk och presenteras inte som en översättning.',originals:'Kundomdömen och verkstadsrapporter finns på originalspråket.',privacyAck:'Jag har läst integritetspolicyn (tyskt original).',languageNote:'Sidorna ger information på ditt valda språk. De innebär inte ett löfte om telefonsupport på det språket.'},
da:{
labels:'Ydelser|Priser|Forløb|Spørgsmål|Kontakt|Anmod om reparation|Ring nu|Læs mere|Forside|Juridiske oplysninger|Privatlivspolitik|Kundeanmeldelser|Reparationsrapporter|Sprog|fra|Gratis|Send forespørgsel|Find vej|Tysk original|Tilbage|Reparationsforespørgsel online|Enhed og fejl|Kontaktoplysninger|Åbn menuen|Luk menuen'.split('|'),
hero:'Reparation af computere, telefoner og spillekonsoller i Augsburg',intro:'Personlig service fra Maurice Keil. Beskriv problemet med din enhed. Vi undersøger fejlen, forklarer mulighederne og aftaler de næste skridt med dig.',hours:'Mandag–lørdag 09.00–20.00. Du er velkommen uden aftale; vi anbefaler at kontakte os først.',
services:[['PC- og laptopreparation','Windows, drivere, programmer, SSD, RAM, rengøring og vedligeholdelse.','En langsom computer behøver ikke altid at blive udskiftet. Vi undersøger årsagen og forklarer, om softwarearbejde, en hurtigere disk, mere hukommelse eller rengøring giver mening. SSD-installation kan omfatte kloning af det eksisterende system. Sikkerhedskopiér vigtige filer på forhånd, hvis muligt. Tiden afhænger af fejlen, arbejdet og reservedelene.'],['Telefon- og tabletreparation','Udskiftning af skærm og batteri, ladestik, bagglas og systemfejl.','Oplys den præcise model, fejlen og synlige skader. Muligheder og samlet pris afhænger af enheden og de nødvendige dele. Vi undersøger enheden, før arbejdet aftales. Lav om muligt en sikkerhedskopi; send ikke adgangskoder, PIN-koder eller oplåsningskoder.'],['Reparation af spillekonsoller','Rengøring og reparation af PlayStation og Xbox, kølepasta og HDMI-porte.','Støjende blæsere, overophedning, uventede nedlukninger eller manglende billede kan have flere årsager. Vi undersøger først modellen og symptomerne. Afhængigt af tilstanden kan rengøring, udskiftning af kølepasta eller HDMI-reparation være relevant. Vi aftaler den forventede pris før start.'],['Softwarebaseret datagendannelse','Analyse af slettede filer og drev med logiske adgangsproblemer.','Stop om muligt med at bruge det berørte drev. Installér ikke programmer, kør ikke reparationsværktøjer, og gem ikke nye filer. Gendannelse kan være mulig, hvis de oprindelige data ikke er helt overskrevet. Resultatet afhænger af drevet og filsystemet; succes garanteres ikke. Vi åbner ikke drev og reparerer ikke fysiske, elektroniske eller mekaniske skader. Disse tilfælde kræver et specialiseret laboratorium.']],
priceNames:'Fejldiagnose|Rådgivning|Systemkontrol|Sikkerhedskopiering|Windows-installation|Driverinstallation|Softwareinstallation|SSD-installation med kloning|RAM-opgradering|Rengøring og vedligeholdelse|Skærmudskiftning|Batteriudskiftning|Reparation af ladestik|Reparation af bagglas|Software- / systemfejl|Analyse til datagendannelse|Vellykket softwarebaseret datagendannelse|PlayStation-rengøring|PlayStation-reparation|Xbox-rengøring|Xbox-reparation|Udskiftning af kølepasta|Reparation af HDMI-port'.split('|'),
fees:'Fejldiagnose koster 30 €, hvis der ikke følger en reparation; gebyret bortfalder, når vi udfører reparationen. Datagendannelse: 55 € for analyse alene eller et mislykket forsøg. Vellykket softwarebaseret gendannelse koster i alt 250 €, inklusive analyse.',terms:'Alle priser er slutpriser; moms angives ikke i henhold til § 19 i den tyske UStG. Fra-priser kan stige på grund af modelspecifikke dele og ekstra arbejde. Vi aftaler det forventede totalbeløb efter undersøgelsen. Reparationer og ekstraarbejde mod betaling starter kun med din godkendelse.',
steps:['Beskriv enheden og fejlen online, telefonisk eller via e-mail.','Vi undersøger enheden og forklarer de relevante muligheder.','Du beslutter efter gennemgang af arbejdet og prisen.','Vi udfører den aftalte reparation, tester enheden og leverer den tilbage.'],
faq:[['Kan jeg komme uden en aftale?','Ja. Kontakt på forhånd hjælper os med at afsætte tilstrækkelig tid til din enhed.'],['Hvor lang tid tager en reparation?','Det afhænger af fejlen og tilgængelige reservedele. Efter undersøgelsen giver vi et realistisk skøn.'],['Bliver mine data behandlet fortroligt?','Vi behandler enheder og data omhyggeligt og fortroligt. Sikkerhedskopiér vigtige filer, hvis muligt; bevarelse af data kan ikke garanteres.'],['Er datagendannelse garanteret?','Nej. De relevante lagerområder skal stadig findes og kunne læses. Helt overskrevne data kan ikke gendannes med denne ydelse.'],['Forpligter forespørgslen mig til en reparation?','Nej. Formularen er kun en forespørgsel. Betalt arbejde starter efter din godkendelse.']],
formIntro:'Beskriv enheden og fejlen, og tilføj kontaktoplysninger. Forespørgslen er uforpligtende.',original:'Følgende tekst er den tyske original. Den er markeret som tysk og præsenteres ikke som en oversættelse.',originals:'Kundeanmeldelser og værkstedsrapporter findes på originalsproget.',privacyAck:'Jeg har læst privatlivspolitikken (tysk original).',languageNote:'Disse sider giver information på det valgte sprog. De lover ikke telefonsupport på det pågældende sprog.'}
};

