export const runtimeRows=`
Bitte dieses Feld ausfüllen.¦Please fill in this field.¦Lütfen bu alanı doldurun.¦Completați acest câmp.¦Заповніть це поле.¦Complete este campo.¦Fyll i detta fält.¦Udfyld dette felt.
Bitte geben Sie eine gültige Telefonnummer für das ausgewählte Land ein.¦Enter a valid phone number for the selected country.¦Seçilen ülke için geçerli bir telefon numarası yazın.¦Introduceți un număr valid pentru țara selectată.¦Введіть дійсний номер для вибраної країни.¦Introduzca un teléfono válido para el país seleccionado.¦Ange ett giltigt telefonnummer för valt land.¦Angiv et gyldigt telefonnummer for det valgte land.
Bitte geben Sie eine gültige Telefonnummer mit Ländervorwahl ein.¦Enter a valid phone number including country code.¦Ülke koduyla birlikte geçerli bir telefon numarası yazın.¦Introduceți un număr valid cu prefix de țară.¦Введіть дійсний номер із кодом країни.¦Introduzca un teléfono válido con prefijo internacional.¦Ange ett giltigt nummer med landskod.¦Angiv et gyldigt nummer med landekode.
Bitte prüfen Sie die markierte Telefonnummer und versuchen Sie es erneut.¦Check the highlighted phone number and try again.¦İşaretli telefon numarasını kontrol edip tekrar deneyin.¦Verificați numărul marcat și încercați din nou.¦Перевірте позначений номер і спробуйте ще раз.¦Revise el teléfono marcado e inténtelo de nuevo.¦Kontrollera det markerade numret och försök igen.¦Kontrollér det markerede nummer, og prøv igen.
Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.¦The enquiry could not be sent. Please try again.¦Talep gönderilemedi. Lütfen tekrar deneyin.¦Solicitarea nu a putut fi trimisă. Încercați din nou.¦Не вдалося надіслати запит. Спробуйте ще раз.¦No se pudo enviar la solicitud. Inténtelo de nuevo.¦Förfrågan kunde inte skickas. Försök igen.¦Forespørgslen kunne ikke sendes. Prøv igen.
Bestätigung wird vorbereitet …¦Preparing confirmation …¦Onay hazırlanıyor …¦Se pregătește confirmarea …¦Підготовка підтвердження …¦Preparando confirmación …¦Förbereder bekräftelse …¦Forbereder bekræftelse …
Die sichere Bestätigungsnummer konnte nicht erstellt werden. Bitte versuchen Sie es erneut.¦The secure confirmation reference could not be created. Please try again.¦Güvenli onay numarası oluşturulamadı. Tekrar deneyin.¦Numărul sigur de confirmare nu a putut fi creat. Încercați din nou.¦Не вдалося створити захищений номер підтвердження. Спробуйте ще раз.¦No se pudo crear la referencia segura de confirmación. Inténtelo de nuevo.¦Det säkra bekräftelsenumret kunde inte skapas. Försök igen.¦Det sikre bekræftelsesnummer kunne ikke oprettes. Prøv igen.
Wird sicher übermittelt …¦Sending securely …¦Güvenli şekilde gönderiliyor …¦Se transmite în siguranță …¦Безпечне надсилання …¦Enviando de forma segura …¦Skickar säkert …¦Sender sikkert …
Antwort von Bigin prüfen¦Check the Bigin response¦Bigin yanıtını kontrol edin¦Verificați răspunsul Bigin¦Перевірте відповідь Bigin¦Compruebe la respuesta de Bigin¦Kontrollera svaret från Bigin¦Kontrollér svaret fra Bigin
Land der Telefonnummer auswählen¦Select phone country¦Telefon ülkesini seçin¦Selectați țara telefonului¦Виберіть країну номера¦Seleccione el país del teléfono¦Välj telefonland¦Vælg telefonland
Liste der Länder¦Country list¦Ülke listesi¦Lista țărilor¦Список країн¦Lista de países¦Landslista¦Landeliste
Land suchen¦Search country¦Ülke ara¦Caută țara¦Знайти країну¦Buscar país¦Sök land¦Søg efter land
Suche löschen¦Clear search¦Aramayı temizle¦Șterge căutarea¦Очистити пошук¦Borrar búsqueda¦Rensa sökning¦Ryd søgning
Keine Suchergebnisse¦No results¦Sonuç yok¦Niciun rezultat¦Нічого не знайдено¦Sin resultados¦Inga resultat¦Ingen resultater
Ein Suchergebnis¦One result¦Bir sonuç¦Un rezultat¦Один результат¦Un resultado¦Ett resultat¦Ét resultat
Suchergebnisse¦Results¦Sonuçlar¦Rezultate¦Результати¦Resultados¦Resultat¦Resultater
`.trim().split('\n').map(line=>line.split('¦'));
export const unconfirmed={
en:'Check the Bigin response below. If it says “Vielen Dank für Ihre Reparaturanfrage” (thank you for your repair enquiry), your enquiry has arrived. This website cannot read that external response automatically. Do not send it again. If no thank-you message appears, call +49 152 54530080.',
tr:'Aşağıdaki Bigin yanıtını kontrol edin. “Vielen Dank für Ihre Reparaturanfrage” (onarım talebiniz için teşekkürler) yazıyorsa talebiniz ulaşmıştır. Site dış yanıtı otomatik okuyamaz. Tekrar göndermeyin. Teşekkür mesajı yoksa +49 152 54530080 numarasını arayın.',
ro:'Verificați răspunsul Bigin de mai jos. Dacă apare „Vielen Dank für Ihre Reparaturanfrage” (vă mulțumim pentru solicitare), cererea a fost primită. Site-ul nu poate citi automat răspunsul extern. Nu retrimiteți. Dacă mesajul lipsește, sunați la +49 152 54530080.',
uk:'Перевірте відповідь Bigin нижче. Якщо є «Vielen Dank für Ihre Reparaturanfrage» (дякуємо за запит на ремонт), запит отримано. Сайт не може автоматично прочитати зовнішню відповідь. Не надсилайте повторно. Якщо повідомлення немає, телефонуйте +49 152 54530080.',
es:'Compruebe la respuesta de Bigin abajo. Si dice «Vielen Dank für Ihre Reparaturanfrage» (gracias por su solicitud), la hemos recibido. El sitio no puede leer automáticamente esa respuesta externa. No vuelva a enviarla. Si no aparece el agradecimiento, llame al +49 152 54530080.',
sv:'Kontrollera svaret från Bigin nedan. Om det står ”Vielen Dank für Ihre Reparaturanfrage” (tack för din förfrågan) har den kommit fram. Webbplatsen kan inte läsa det externa svaret automatiskt. Skicka inte igen. Om tackmeddelandet saknas, ring +49 152 54530080.',
da:'Kontrollér svaret fra Bigin nedenfor. Hvis der står ”Vielen Dank für Ihre Reparaturanfrage” (tak for din forespørgsel), er den modtaget. Siden kan ikke læse det eksterne svar automatisk. Send ikke igen. Mangler beskeden, så ring +49 152 54530080.'
};

